# Alacritty Configuration (TOML)
# generate by ChatGPT: https://chatgpt.com/share/e1e78d5c-18a0-4736-b694-cfd4f2977a62

[colors.primary]
background = "#1C1C1E"   # Primary Background
foreground = "#EBEBF5"   # Primary Text

[colors.normal]
black = "#1C1C1E"        
red = "#EB4E3D"          
green = "#34C759"        
yellow = "#F7CE46"       
blue = "#007AFF"         
magenta = "#AF52DE"      
cyan = "#5AC8FA"         
white = "#EBEBF5"        

[colors.bright]
black = "#4A4A4A"        
red = "#FF453A"          
green = "#30D158"        
yellow = "#FFD60A"       
blue = "#0A84FF"         
magenta = "#BF5AF2"      
cyan = "#64D2FF"         
white = "#F2F2F7"        

[colors.cursor]
text = "#1C1C1E"         # Text Color within the cursor
cursor = "#F2F2F7"       # Cursor Color

[colors.selection]
text = "#1C1C1E"         # Selected Text
background = "#5AC8FA"   # Selection Background (System Teal)

# 1. Space Gray
# Hex: #888888
# RGB: (136, 136, 136)
# Description: Space Gray is a signature color for Apple, often seen in their devices like iPhones, iPads, and MacBooks. It’s a dark, metallic gray with a slightly cool tone, embodying a premium and modern look.
# 2. Silver
# Hex: #C0C0C0
# RGB: (192, 192, 192)
# Description: Silver is another classic Apple color, used primarily in devices like MacBooks and iMacs. It’s a light gray with a metallic sheen, representing sophistication and simplicity.
# 3. Light Gray
# Hex: #E0E0E0
# RGB: (224, 224, 224)
# Description: Light Gray is often used in backgrounds, borders, and subtle UI elements. It’s a soft, neutral gray that provides a calm and unobtrusive backdrop.
# 4. Dark Gray
# Hex: #A9A9A9
# RGB: (169, 169, 169)
# Description: Dark Gray is used for more prominent elements like text or icons. It’s a medium-dark tone that offers good contrast while maintaining a subdued, professional appearance.
# 5. Graphite
# Hex: #4A4A4A
# RGB: (74, 74, 74)
# Description: Graphite is a deeper, richer gray used in darker themes or as an accent color. It’s close to black but with enough gray to keep it from being too harsh.
# 6. Charcoal Gray
# Hex: #3A3A3A
# RGB: (58, 58, 58)
# Description: Charcoal Gray is a very dark gray, often used in macOS's Dark Mode. It’s almost black but still retains the softness and depth characteristic of gray tones.
