cheatpaths:
  - name: community # a name for the cheatpath
    path: ~/.config/cheat/cheatsheets/community # the path's location on the filesystem
    tags: [community] # these tags will be applied to all sheets on the path
    readonly: true

  - name: personal
    path: "~/.config/cheat/cheatsheets/personal" # this is a separate directory and repository than above
    # path: "~/.dotfiles/.profiles/personal/cheat"  # this is a separate directory and repository than above
    tags: [personal]
    readonly: false # new sheets may be written here
